# -*- coding: utf-8 -*-
"""bigdata-TP4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KQIW0h-B2sr46gexuijgiY2Iw910U6L8
"""

input_csv = "/Real_Estate_Sales_2001-2022_GL.csv"
output_dir = "/output"

import pandas as pd
import os

file_path = os.getenv("input_csv", "Real_Estate_Sales_2001-2022_GL.csv") #/content/drive/MyDrive/Colab Notebooks/Real_Estate_Sales_2001-2022_GL.csv
df = pd.read_csv(file_path, low_memory=False)
df.head()
df.info()

import pandas as pd
import numpy as np

file_path = "Real_Estate_Sales_2001-2022_GL.csv" #/content/drive/MyDrive/Colab Notebooks/Real_Estate_Sales_2001-2022_GL.csv

dtype_text = {
    "Property Type": "string",
    "Residential Type": "string",
    "Non Use Code": "string",
    "Assessor Remarks": "string",
    "OPM remarks": "string",
    "Town": "string",
    "Address": "string",
    "Location": "string"
}

df = pd.read_csv(file_path, dtype=dtype_text, low_memory=False)

# تحويل التاريخ
df["Date Recorded"] = pd.to_datetime(df["Date Recorded"], errors="coerce")

for col in ["Assessed Value", "Sale Amount", "Sales Ratio"]:
    df[col] = pd.to_numeric(df[col], errors="coerce")

for col in ["Town", "Property Type", "Residential Type", "Non Use Code"]:
    df[col] = df[col].astype("category")

df.info(memory_usage="deep")

"""جودة البيانات"""

print("القيم المفقودة في كل عمود:")
missing = df.isna().sum().sort_values(ascending=False)
print(missing)

# نحتفظ بالصفوف التي تحتوي على تاريخ و مبلغ بيع
df = df.dropna(subset=["Date Recorded", "Sale Amount"])

# إزالة المبيعات صفر أو أقل
df = df[df["Sale Amount"] > 0]

# إذا وجدت قيم تقييم (Assessed Value) سالبة أو غير منطقية نحذفها
df = df[df["Assessed Value"] >= 0]

print(f"\n عدد الصفوف بعد التنظيف الأولي: {len(df):,}")


duplicates = df.duplicated(subset=["Serial Number", "Date Recorded", "Address"], keep=False).sum()
print(f" الصفوف المكررة: {duplicates}")

df = df.drop_duplicates(subset=["Serial Number", "Date Recorded", "Address"], keep="first")
print(f" عدد الصفوف بعد إزالة التكرارات: {len(df):,}")

# نملأ القيم المفقودة بـ "Unknown"
text_cols = ["Property Type", "Residential Type", "Non Use Code", "Assessor Remarks", "OPM remarks", "Location"]
for col in text_cols:
    if df[col].dtype.name == "category":
        # إضافة الفئة الجديدة "Unknown" إذا لم تكن موجودة
        if "Unknown" not in df[col].cat.categories:
            df[col] = df[col].cat.add_categories(["Unknown"])
        #  نملأ القيم الفارغة
        df[col] = df[col].fillna("Unknown")
    else:
        # الأعمدة النصية العادية
        df[col] = df[col].fillna("Unknown")


#  استخراج السنة والشهر من التاريخ
df["Year"] = df["Date Recorded"].dt.year
df["Month"] = df["Date Recorded"].dt.month
print("\n📆 تم إنشاء الأعمدة الزمنية بنجاح (Year, Month)")

print("\nملخص بعد التنظيف:")
print(df.info(memory_usage="deep"))
print(df.head())

"""التحليل الاستكشافي

الإحصاءات الوصفية
"""

print("  إحصائيات الأعمدة الرقمية:")
print(df[["Assessed Value", "Sale Amount", "Sales Ratio"]].describe().T)

print("\n عدد المدن الفريدة:", df["Town"].nunique())
print(" عدد أنواع العقارات:", df["Property Type"].nunique())
print(" عدد أنواع السكن:", df["Residential Type"].nunique())

print("\n أكثر 5 مدن من حيث عدد عمليات البيع:")
print(df["Town"].value_counts().head(5))

"""المبيعات حسب السنة"""

import matplotlib.pyplot as plt

sales_by_year = df.groupby("Year")["Sale Amount"].sum()

plt.figure(figsize=(10,5))
sales_by_year.plot(kind="bar", color="skyblue")
plt.title("Total sales by year")
plt.xlabel("year")
plt.ylabel("Total sales")
plt.grid(axis="y", linestyle="--", alpha=0.6)
plt.show()

"""حسب الشهر لكل السنوات"""

sales_by_month = df.groupby("Month")["Sale Amount"].sum()

plt.figure(figsize=(10,5))
sales_by_month.plot(kind="bar", color="orange")
plt.title("Total sales by month")
plt.xlabel("month")
plt.ylabel("Total sales")
plt.grid(axis="y", linestyle="--", alpha=0.6)
plt.show()

"""حسب المدن"""

sales_by_town = df.groupby("Town")["Sale Amount"].sum().sort_values(ascending=False).head(10)

plt.figure(figsize=(12,6))
sales_by_town.plot(kind="bar", color="green")
plt.title(" Top 10 cities in terms of total sales")
plt.xlabel("cities")
plt.ylabel("total sales (USD)")
plt.xticks(rotation=45)
plt.grid(axis="y", linestyle="--", alpha=0.6)
plt.show()

"""أنواع العقارات"""

sales_by_type = df.groupby("Property Type")["Sale Amount"].sum().sort_values(ascending=False)

plt.figure(figsize=(10,5))
sales_by_type.plot(kind="bar", color="purple")
plt.title("Total sales by property type")
plt.xlabel("property type")
plt.ylabel("Total sales (USD)")
plt.xticks(rotation=45)
plt.grid(axis="y", linestyle="--", alpha=0.6)
plt.show()

filtered = df[df["Property Type"] != "Unknown"]
sales_by_type = filtered.groupby("Property Type")["Sale Amount"].sum().sort_values(ascending=False)

plt.figure(figsize=(10,5))
sales_by_type.plot(kind="bar", color="purple")
plt.title("Total sales by property type (excluding Unknown)")
plt.xlabel("Property Type")
plt.ylabel("Total Sales (USD)")
plt.xticks(rotation=45)
plt.grid(axis="y", linestyle="--", alpha=0.6)
plt.show()

df["Property Type"].value_counts().head(10).plot(kind="bar", color="teal")
plt.title("Number of records by property type")
plt.ylabel("Count of records")
plt.show()

"""العلاقة بين القيمة التقييمية وسعر البيع"""

import seaborn as sns

plt.figure(figsize=(8,6))
sns.scatterplot(x="Assessed Value", y="Sale Amount", data=df.sample(5000), alpha=0.5)
plt.xscale('log')
plt.yscale('log')
plt.title("Relationship between assessed and sale price (log scale)")
plt.xlabel("Assessed Value (log scale)")
plt.ylabel("Sale Amount (log scale)")
plt.show()

filtered = df[(df["Assessed Value"] < 2_000_000) & (df["Sale Amount"] < 2_000_000)]
sns.scatterplot(x="Assessed Value", y="Sale Amount", data=filtered.sample(5000), alpha=0.5)
plt.title("Relationship between assessed and sale price (filtered data)")
plt.show()

correlation = df["Assessed Value"].corr(df["Sale Amount"])
print(f" معامل الارتباط بين التقييم وسعر البيع: {correlation:.2f}")

"""توزيع أسعار المبيعات"""

sns.histplot(df["Sale Amount"], bins=50, color="teal")
plt.yscale('log')
plt.title("Distribution of sales prices")
plt.xlabel("Sale Amount (USD)")
plt.ylabel("Number of transactions(log)")
plt.show()

summary_stats = df[["Assessed Value", "Sale Amount", "Sales Ratio"]].describe()
summary_stats.to_csv("/content/drive/MyDrive/Colab Notebooks/sales_summary_stats.csv")
print("تم")

"""التحليل المتقدم

Regression تنبؤ بسعر البيع
"""

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
import numpy as np

#  الأعمدة المفيدة التي نحتاج
model_df = df[["Assessed Value", "Sale Amount", "Town", "Property Type", "Residential Type"]].copy()

# إزالة القيم المفقودة
model_df = model_df.dropna()

# تحويل الأعمدة النصية إلى أرقام (Encoding)
model_df = pd.get_dummies(model_df, drop_first=True)

# تقسيم البيانات
X = model_df.drop("Sale Amount", axis=1)
y = model_df["Sale Amount"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# تدريب
model = LinearRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

# تقييم النموذج
r2 = r2_score(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))

print(f" R² Score: {r2:.3f}")
print(f" RMSE: {rmse:,.2f} USD")

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score
import matplotlib.pyplot as plt
import seaborn as sns

data = df.copy()

# استبعاد القيم الشاذة
filtered = data[(data["Sale Amount"] < 2_000_000) & (data["Assessed Value"] < 2_000_000)].copy()

filtered["Log_Sale"] = np.log1p(filtered["Sale Amount"])
filtered["Log_Assessed"] = np.log1p(filtered["Assessed Value"])

# اختيار الأعمدة المهمة للنموذج
features = ["Log_Assessed", "Year", "Sales Ratio"]
filtered = filtered.dropna(subset=features + ["Log_Sale"])

X = filtered[features]
y = filtered["Log_Sale"]

# تقسيم Train/Test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

lin_model = LinearRegression()
lin_model.fit(X_train, y_train)

y_pred_lin = lin_model.predict(X_test)

# تقييم الأداء
r2_lin = r2_score(y_test, y_pred_lin)
rmse_lin = np.sqrt(mean_squared_error(y_test, y_pred_lin))

print(" Linear Regression Results:")
print(f"R² Score: {r2_lin:.3f}")
print(f"RMSE (log-scale): {rmse_lin:.3f}")

# من  log الى القيم الحقيقية
y_test_real = np.expm1(y_test)
y_pred_real = np.expm1(y_pred_lin)

plt.figure(figsize=(6,6))
sns.scatterplot(x=y_test_real, y=y_pred_real, alpha=0.4)
plt.xlabel("Actual Sale Amount (USD)")
plt.ylabel("Predicted Sale Amount (USD)")
plt.title("Linear Regression: Actual vs Predicted")
plt.plot([0, max(y_test_real)], [0, max(y_test_real)], 'r--')
plt.show()

rf_model = RandomForestRegressor(
    n_estimators=150,
    max_depth=None,
    random_state=42,
    n_jobs=-1
)

rf_model.fit(X_train, y_train)
y_pred_rf = rf_model.predict(X_test)

r2_rf = r2_score(y_test, y_pred_rf)
rmse_rf = np.sqrt(mean_squared_error(y_test, y_pred_rf))

print(f"R² Score: {r2_rf:.3f}")
print(f"RMSE (log-scale): {rmse_rf:.3f}")

importances = rf_model.feature_importances_
feature_names = X.columns

plt.figure(figsize=(6,4))
sns.barplot(x=importances, y=feature_names, color="skyblue")
plt.title("Feature Importance - Random Forest")
plt.xlabel("Importance Score")
plt.ylabel("Feature")
plt.show()

"""Clustering تقسيم السوق"""

from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans

# نختار الأعمدة العددية فقط
cluster_df = df[["Assessed Value", "Sale Amount", "Sales Ratio"]].copy()
cluster_df = cluster_df.dropna()

# مقياس موحد
scaler = StandardScaler()
X_scaled = scaler.fit_transform(cluster_df)

# تجربة K-Means مع 4 مجموعات
kmeans = KMeans(n_clusters=4, random_state=42, n_init=10)
df["Cluster"] = kmeans.fit_predict(X_scaled)

df["Cluster"].value_counts()

sns.scatterplot(
    x="Assessed Value",
    y="Sale Amount",
    hue="Cluster",
    data=df.sample(5000),
    palette="viridis"
)
plt.title("KMeans Clusters: Property Groups")
plt.show()

"""تجهيز ملف Power BI"""

import pandas as pd
import numpy as np

#   البيانات النماذج
export_df = filtered.copy()

# إضافة التنبؤات من النماذج
export_df["Predicted_Linear"] = np.expm1(lin_model.predict(X))
export_df["Predicted_RF"] = np.expm1(rf_model.predict(X))

# حساب النسبة بين سعر البيع والتقييم
export_df["Sale_to_Assess_Ratio"] = export_df["Sale Amount"] / export_df["Assessed Value"]

# حساب الخطأ في التنبؤ (من نموذج الغابة العشوائية)
export_df["Error_RF"] = export_df["Sale Amount"] - export_df["Predicted_RF"]

#  الأعمدة النهائية
final_columns = [
    "Serial Number", "Date Recorded", "Year", "Month", "Town", "Address",
    "Assessed Value", "Sale Amount", "Sales Ratio", "Property Type", "Residential Type",
    "Predicted_Linear", "Predicted_RF", "Sale_to_Assess_Ratio", "Error_RF"
]

final_df = export_df[final_columns]

# حفظ الملف
output_path = "/content/drive/MyDrive/Colab Notebooks/RealEstate_Final_For_PowerBI.csv"
final_df.to_csv(output_path, index=False)

print(f" تم حفظ ملف التحليل النهائي بنجاح إلى: {output_path}")
print(f"إجمالي عدد السجلات في الملف: {len(final_df):,}")

"""رفع الملف إلى Google Sheets"""

df.to_csv("/content/RealEstate.csv", index=False)

from google.colab import auth
auth.authenticate_user()

import gspread
from google.auth import default
from gspread_dataframe import set_with_dataframe
import pandas as pd

file_path = "/content/drive/MyDrive/Colab Notebooks/RealEstate_Final_For_PowerBI.csv"
df = pd.read_csv(file_path)

# اختيار الأعمدة المهمة فقط
cols_to_keep = [
    "Town",
    "Property Type",
    "Assessed Value",
    "Sale Amount",
    "Year",
    "Month"
]
df_small = df[cols_to_keep].head(800000)

creds, _ = default()

# الاتصال بـ Google Sheets
gc = gspread.authorize(creds)

# إنشاء ملف جديد في Google Drive
sh = gc.create("RealEstate_Sales_Data")

worksheet = sh.get_worksheet(0)

set_with_dataframe(worksheet, df_small)

print("✅ تم رفع البيانات بنجاح إلى Google Sheets!")
print("📄 رابط الملف:", sh.url)
